---

language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  - pip install ansible

script:
  - bash tests/test.sh
  - curl http://localhost:10080
