---

- name: APT | Install packages
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{ jenkins_packages }}"

- name: APT_KEY | Install Jenkins key
  apt_key: url=http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key state=present

- name: APT_REPOSITORY | Add Jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian-stable binary/' state=present

- name: APT | Install Jenkins (from APT)
  apt: pkg=jenkins state=present
  when: jenkins_version is none

- name: APT | Install Jenkins version (from HTTP)
  apt: deb="http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_{{ jenkins_version }}_all.deb"
  when: jenkins_version is not none
