---

- name: APT | Install PHP related packages
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items: jenkins_php_packages

- name: APT_KEY | Install Jenkins key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: APT_REPOSITORY | Add Jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: APT | Install Jenkins
  apt: pkg=jenkins state=present
  register: apt

- name: SERVICE | Ensure Jenkins is started
  service: name=jenkins state=started
  register: service

- name: WAIT_FOR | Wait for jenkins running
  wait_for: port={{ jenkins_port }} delay=60
  when: apt.changed or service.changed

