---

- name: GET_URL | Update plugin list
  get_url: url=http://updates.jenkins-ci.org/update-center.json dest={{ jenkins_update_json }} mode=0440
  register: plugin_updates

- name: SHELL | Update plugin list in Jenkins
  shell: "sed '1d;$d' {{ jenkins_update_json }} | curl -X POST -H 'Accept: application/json' -d @- http://localhost:{{ jenkins_port }}/updateCenter/byId/default/postBack"
  when: plugin_updates.changed

- name: SHELL | List plugins
  shell: java -jar {{ jenkins_cli }} -s http://localhost:{{ jenkins_port }} list-plugins | cut -f 1 -d ' '
  register: plugins_installed
  changed_when: false

- name: COMMAND | Install Jenkins plugins
  command: java -jar {{ jenkins_cli }} -s http://localhost:{{ jenkins_port }} install-plugin {{ item }}
  with_flattened:
    - jenkins_plugins
    - jenkins_extra_plugins
  when: item not in plugins_installed.stdout_lines
  notify: safe-restart jenkins
