---

- name: JENKINS_PLUGIN | Install...
  jenkins_plugin:
    name: "{{ item }}"
    url: "http://localhost:{{ jenkins_http_port }}"
    timeout: 120
    params:
      url_username: "{{ jenkins_admin_username }}"
      url_password: "{{ jenkins_admin_password }}"
  with_flattened:
    - "{{ jenkins_plugins }}"
    - "{{ jenkins_extra_plugins }}"
  notify: restart jenkins


