---

- name: SHELL | List plugins
  shell: java -jar {{ jenkins_cli }} -s http://localhost:{{ jenkins_port }} list-plugins | cut -f 1 -d ' '
  register: plugins_installed
  changed_when: false

- name: COMMAND | Install Jenkins plugins
  command: java -jar {{ jenkins_cli }} -s http://localhost:{{ jenkins_port }} install-plugin {{ item }}
  with_flattened:
    - jenkins_plugins
    - jenkins_extra_plugins
  when: >
    jenkins_force_install_plugins or
    item not in plugins_installed.stdout_lines
  notify: safe-restart jenkins
